[tool.flake8]
exclude = [
  '.git',
  '_*',
  'rl',
  'wandb',
]
extend-ignore = ['E203']
max-line-length = 99

[tool.pytest.ini_options]
norecursedirs = [
  '.git',
  '_*',
  'rl',
]

[tool.cibuildwheel]
skip = ["*linux_i686*"]

[tool.cibuildwheel.linux]
environment = { OPAMROOTISOK = 1 }
before-all = "make manylinux-opam cibuildwheel-setup"

[[tool.cibuildwheel.overrides]]
select = "*-musllinux*"
before-all = "make musllinux-opam cibuildwheel-setup"
