[build-system]
requires = ["setuptools>=64", "setuptools_scm>=8", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
root = "../.."
git_describe_command = "git describe --long --tags --match 'v*'"
