name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  build_wheels:
    name: Build Python wheels
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-11]

    steps:
      - uses: actions/checkout@v3

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.11.3

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: ./wheelhouse/*.whl

  gh_release:
    name: Create Github release
    runs-on: ubuntu-latest

    needs: build_wheels

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: wheels
          path: wheels

      - name: Create release
        uses: svenstaro/upload-release-action@v2
        with:
          body: "Automatic release from version tag."
          prerelease: ${{ contains(github.ref_name, '+') }}
          file: 'wheels/*.whl'
          file_glob: true

  pypi_release:
    name: Push to PyPI
    runs-on: ubuntu-latest

    needs: build_wheels

    if: ${{ ! contains(github.ref_name, '+') }}

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: wheels
          path: dist

      - name: Push to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_TOKEN }}
