on:
  push:
    tags:
      - 'v*'

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-11]

    steps:
      - uses: actions/checkout@v3

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.11.3

      - uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: ./wheelhouse/*.whl

  gh_release:
    runs-on: ubuntu-latest

    needs: build_wheels

    steps:
      - name: Download wheels
        uses: actions/download-artifact@v3
        with:
          name: wheels
          path: wheels

      - name: Create Github Release
        uses: svenstaro/upload-release-action@v2
        with:
          body: "Automatic release from version tag."
          prerelease: ${{ contains(tag, '+') }}
          file: 'wheels/*.whl'
          file_glob: true
